
PAC_IDS = [
        'C00208322', # MANAGEMENT AND TRAINING CORPORATION POLITICAL ACTION COMMITTEE 
        'C00366468', # CORECIVIC, INC. POLITICAL ACTION COMMITTEE 
        'C00382150'] # THE GEO GROUP, INC. POLITICAL ACTION COMMITTEE 



